name: Xodium CI/CD - Docker Image Build & Publish
run-name: "Xodium CI/CD - Docker Image Build & Publish"

on: { push: { branches: [ main ] } }

concurrency: { group: "${{ github.workflow }}-${{ github.ref }}", cancel-in-progress: true }

permissions: { contents: read, packages: write }

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: { name: "${{ github.ref_name }}", url: "${{ env.url }}" }
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: login_docker_registry
        name: Log in to GitHub Container Registry
        uses: docker/login-action@3d100841f68d4548bf57e52eb27bd33ec5069f55
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: extract_version
        name: Extract version from pyproject.toml
        run: |
          VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - id: build_docker_image
        name: Build Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_NAME/illyrion:${{ env.VERSION }} .
          docker build -t ghcr.io/$REPO_NAME/illyrion:latest .

      - id: push_docker_image
        name: Push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO_NAME/illyrion:${{ env.VERSION }}
          docker push ghcr.io/$REPO_NAME/illyrion:latest
          echo "url=https://ghcr.io/$REPO_NAME/illyrion:${{ env.VERSION }}" >> $GITHUB_ENV